name: Create Release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Upload build artifacts to release
      uses: actions/upload-artifact@v3
      with:
        name: BuildFiles
        path: ./*/build/libs/*.jar
    - name: Generate versions
      uses: HardNorth/github-version-generate@v1.3.0
      with:
        version-source: file
        version-file: build.gradle
        version-file-extraction-pattern: '(?<=version=).+'
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ./*/build/libs/*.jar
        name: ${{ env.RELEASE_VERSION }}
        generate_release_notes: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
